# Lab 4: NumPy Introduction

### Author: <font color='red'>Charles Moore</font>

## Verify installation of NumPy

If the NumPy library is installed, it can be imported with the standard Python import statement.
NumPy is usually imported using the **np** alias. The version of NumPy can be verified with the \_\_version\_\_ command.


In [1]:
# Make sure NumPy is installed (see Lab Instructions if you get an error here)
import numpy as np
np.__version__

'1.20.1'

## Intro to NumPy (100 pts)

## Step A: Creating NumPy Arrays (30 pts)

__Create a NumPy ndarray Object__

NumPy works with arrays. The array object used in NumPy is called __ndarray__ which is shorthand for __N-dimensional array__ (an array with any number of dimensions). The __ndarray__ is a _homogeneous_ array, meaning all the values within the array must be of the same datatype.

All you need to create a simple array is pass it a list, tuple or any array-like object and it will be converted into an __ndarray__. Like Python, NumPy will determine the datatype based on the values used to create the array, however you CAN specify the datatype using the __dtype = 'xxxx'__ option. 

NumPy has several functions that can be used to create arrays with __initial values__. A list of the creation routines can be found on the NumPy API reference website: 

- https://numpy.org/doc/stable/reference/routines.array-creation.html 

Here are a few commonly used routines:
- np.zeros ~ returns an array of a given shape and type filled with _zeros_ (0)
- np.ones  ~ returns an array of a given shape and type filled with _ones_ (1) 
- np.full  ~ returns an array of a given shape and type filled with a _fill_value_
- np.empty ~ returns an array of a given shape and type without initializing entries
- np.eye   ~ returns a 2D-array with 1's on a diagonal and 0's elsewhere
- np.identity ~ returns a square array with ones on the __main__ diagonal (similar to np.eye)

Let's create a few ...

<span style="color:blue">
1. Create a <strong>NumPy</strong> array <strong>A1</strong> using a <strong>list</strong> containing <strong>[5,10,15,20,25]</strong>. <br>
2. Create a <strong>NumPy</strong> array <strong>A2</strong> using a <strong>list</strong> containing <strong>[5,10,15,20,25]</strong> but explicitly set the <strong>data type to float (64)</strong>. <br>
3. Create a <strong>NumPy</strong> array <strong>A3</strong> using a <strong>tuple</strong> containing <strong>(1,2,3,4,5)</strong>. <br>    
4. Create a <strong>NumPy</strong> array <strong>A4</strong> with <strong>4 elements</strong> all set to <strong>0</strong> and <strong>float</strong>. <br>
5. Create a <strong>2 x 2 NumPy</strong> array <strong>A5</strong> with all the values set to <strong>1</strong> and <strong>int</strong>. <br>       
6. Create a <strong>3 x 3 NumPy</strong> array <strong>A6</strong> with all values set to <strong>2021</strong>. <br>
7. Create a <strong>4 x 4 NumPy</strong> array <strong>A7</strong> without initializing the entries<br>     
8. Create a <strong>5 x 5 NumPy</strong> array <strong>A8</strong> with the index of the diagonal <strong>k=2</strong> values set to <strong>1</strong>. <br> 
9. Create a <strong>5 x 5 NumPy</strong> array <strong>A9</strong> with the <strong>main</strong> diagonal values set to <strong>1</strong>. <br> 
10. Create a <strong>2 x 5 NumPy</strong> array <strong>A10</strong> using a <strong>list</strong> containing values <strong>1-10 (inclusive)</strong> using <strong>range()</strong> to generate the values for both rows.
</span>

In [45]:
# INSERT CODE FOR STEPS 1 - 10
import numpy as np
A1 = np.array([5,10,15,20,25])
A2 = np.array([5,10,15,20,25], dtype='float')
A3 = np.array((1,2,3,4,5))
A4 = np.zeros(4, dtype='float')
A5 = np.ones([2,2],dtype = 'int')
A6 = np.full([3,3],2021)
A7 = np.empty([4,4])
A8 = np.eye(5, k=2)
A9 = np.eye(5)
A10 = np.array([[list(range(1,6))],[list(range(6,11))]])

In [46]:
# DO NOT MODIFY !!!
print("A1:\n",A1)
print("A2:\n",A2)
print("A3:\n",A3)
print("A4:\n",A4)
print("A5:\n",A5)
print("A6:\n",A6)
print("A7:\n",A7)
print("A8:\n",A8)
print("A9:\n",A9)
print("A10:\n",A10)

A1:
 [ 5 10 15 20 25]
A2:
 [ 5. 10. 15. 20. 25.]
A3:
 [1 2 3 4 5]
A4:
 [0. 0. 0. 0.]
A5:
 [[1 1]
 [1 1]]
A6:
 [[2021 2021 2021]
 [2021 2021 2021]
 [2021 2021 2021]]
A7:
 [[4.65844522e-310 0.00000000e+000 2.41907520e-312 2.37663529e-312]
 [2.22809558e-312 2.46151512e-312 6.79038654e-313 2.35541533e-312]
 [2.46151512e-312 6.79038654e-313 2.35541533e-312 6.79038654e-313]
 [2.14321575e-312 2.22809558e-312 2.14321575e-312 7.31973418e+169]]
A8:
 [[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
A9:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
A10:
 [[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]


__Create a NumPy ndarray with Numerical ranges & Random__

NumPy has several functions that can be used to create arrays with __numerical ranges__. A list of the numerical range routines can be found on the NumPy API reference website: 
- https://numpy.org/doc/stable/reference/routines.array-creation.html#numerical-ranges

Here are a few commonly used routines:
- np.arange    ~ return evenly spaced values within a given interval
- np.linspace  ~ return evenly spaced numbers over a specified interval
- np.logspace  ~ returns numbers spaced evenly on a log scale

NOTE: You also might want to create arrays of random numbers! This can be done as well using Python's __random__ and __randint__ methods. As always, w3schools is a great place to find a list of all the __random module methods__ 

https://www.w3schools.com/python/module_random.asp

- seed()    ~ initializes the random number generator
- randint() ~ returns a random number between a given range
- random()  ~ returns a random float number between 0 and 1

Let's try a few ...

<span style="color:blue">
    11. Create a <strong>NumPy</strong> array <strong>A11</strong> using <strong>arange</strong> with sequential values from <strong>1-12 (inclusive)</strong>. <br>  
    12. Create a <strong>NumPy</strong> array <strong>A12</strong> using <strong>linspace</strong> with <strong>5</strong> values evenly spaced between <strong>10 - 50</strong>. <br> 
    13. Create a <strong>NumPy</strong> array <strong>A13</strong> using <strong>logspace</strong> with <strong>10</strong> values evenly spaced between base start <strong>2</strong> and base stop <strong>3</strong>. <br>     
    14. Create a <strong>NumPy</strong> array <strong>A14</strong> using <strong>random</strong> to generate <strong>5</strong> random numbers between <strong>0 - 1</strong>. <br>
    15. Create a <strong>2 x 3 NumPy</strong> array <strong>A15</strong> using <strong>randint</strong> to generate random integers between <strong>0 - 5</strong>. <br>
</span>

In [56]:
import random
# INSERT CODE FOR STEPS 11 - 15
import numpy as np
A11 = np.arange(1,13)
A12 = np.linspace(10,50,num=5)
A13 = np.logspace(2,3,num=10)
A14 = np.random.rand(1,5)
A15 = np.random.randint(0,5,(2,3))

In [57]:
# DO NOT MODIFY !!!
print("A11:\n",A11)
print("A12:\n",A12)
print("A13:\n",A13)
print("A14:\n",A14)
print("A15:\n",A15)

A11:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
A12:
 [10. 20. 30. 40. 50.]
A13:
 [ 100.          129.1549665   166.81005372  215.443469    278.25594022
  359.38136638  464.15888336  599.48425032  774.26368268 1000.        ]
A14:
 [[0.18132409 0.2819481  0.00471999 0.86217722 0.80957154]]
A15:
 [[1 4 2]
 [0 1 0]]


## Step B: The Basics of NumPy Arrays (70 pts)
### Array Attributes, Indexing, Slicing, Reshaping, Joining and Splitting

__Review the Attributes of ndarray Objects__

As with other data objects, you can determine various attributes associated with each ndarray.
A list of the array attributes can be found on the NumPy API reference website:
- https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-attributes

Here are a few:
- ndarray.ndim  ~ number of array dimensions
- ndarray.shape ~ tuple of array dimensions
- ndarray.size  ~ number of elements in the array
- ndarray.dtype ~ data-type of the array's elements
- ndarray.itemsize ~ length of one array element in bytes
- ndarray.nbytes   ~ total bytes consumed by the elements of the array


Let's create an array and check it's attributes ...

__ARRAY ATTRIBUTES__

<span style="color:blue">
    1. Create a <strong>4 x 4 NumPy</strong> array <strong>B1</strong> filled with <strong>1's</strong> of type <strong>int</strong>. <br>
    2. Set <strong>B2</strong> = the <strong>number of dimensions</strong> of B1. <br>   
    3. Set <strong>B3</strong> = the <strong>size of each dimension</strong> of B1. <br>  
    4. Set <strong>B4</strong> = the <strong>total size</strong> of B1. <br>  
    5. Set <strong>B5</strong> = the <strong>data type</strong> of B1. <br>  
    6. Set <strong>B6</strong> = the <strong>size (in bytes) of each array element</strong> of B1. <br>  
    7. Set <strong>B7</strong> = the <strong>total size (in bytes)</strong> of B1.  
</span>

In [75]:
# INSERT CODE FOR STEPS 1 - 7
import numpy as np
B1 = np.ones([4,4],dtype='int')
B2 = B1.ndim
B3 = B1.shape
B4 = B1.size
B5 = B1.dtype
B6 = B1.itemsize
B7 = B6*B4

In [67]:
# DO NOT MODIFY !!!
print("B1:\n",B1)
print("B2:",B2)
print("B3:",B3)
print("B4:",B4)
print("B5:",B5)
print("B6:",B6)
print("B7:",B7)

B1:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
B2: 2
B3: (4, 4)
B4: 16
B5: int64
B6: 8
B7: 128


__Review Array Indexing__

As with regular Python arrays, __ndarrays__ can be indexed the same as in Python, __array[__ _index_ __]__. Array indexing is the same as accessing an array element -- you refer to the element's index number. 

__REMEMBER: Array indexes start with 0 !__

w3schools.com has some good information on NumPy Array Indexing:
- https://www.w3schools.com/python/numpy_array_indexing.asp
        
Let's create an array and and do some indexing ...

TERMINOLOGY CLARIFICATION FOR THESE QUESTIONS:
- index 5 = array[5]
- element 5 = array[4]

__ARRAY INDEXING__

<span style="color:blue">
    8. Create a <strong>NumPy</strong> array <strong>B8</strong> using <strong>arange</strong> with values <strong>5 - 15 (inclusive)</strong>. <br>
    9. Set <strong>B9</strong> = the <strong>1st</strong> element in B8. <br>
    10. Set <strong>B10</strong> = the <strong>9th</strong> element in B8. <br> 
    11. Set <strong>B11</strong> =  the <strong>9th</strong> element of B8 using <strong>negative indexing</strong>. <br>
    12. Set <strong>B12</strong> =  <strong>every other element</strong> of B8 (starting with the 1st element). <br>  
    13. Set <strong>B13</strong> =  B8 in <strong>reverse order</strong> using <strong>negative indexing</strong> [DO NOT USE reverse() METHOD!]<br>
    14. Set <strong>B14</strong> = the <strong>5th thru 8th (inclusive)</strong> element of B8
</span>

In [93]:
# INSERT CODE FOR STEPS 8 - 14
import numpy as np
B8 = np.arange(5,16)
B9 = B8[0]
B10 = B8[9]
B11 = B8[-2]
B12 = []
B13 = []
for i in range(0,B8.size,2):
    B12.append(B8[i])
for i in range(len(B8)-1,-1, -1):
    B13.append(B8[i])
B14 = np.array(B8[5:9])

In [91]:
# DO NOT MODIFY !!!
print("B8:\n",B8)
print("B9:\n",B9)
print("B10:\n",B10)
print("B11:\n",B11)
print("B12:\n",B12)
print("B13:\n",B13)
print("B14:\n",B14)

B8:
 [ 5  6  7  8  9 10 11 12 13 14 15]
B9:
 5
B10:
 14
B11:
 14
B12:
 [5, 7, 9, 11, 13, 15]
B13:
 [15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5]
B14:
 [10 11 12 13]


__Review Array Slicing__

As with regular Python arrays, __ndarrays__ can be sliced using the extended Python slicing syntax, __array[__   _start:end:step_ __]__. 

w3schools.com has some good information on NumPy Array Slicing:
- https://www.w3schools.com/python/numpy_array_slicing.asp
        
Let's create an array and do some slicing ...

__ARRAY SLICING__

<span style="color:blue">
    15. Create a <strong>5 x 5 NumPy</strong> array <strong>B15</strong> using values <strong>[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,12,11],[10,9,8,7,6],[5,4,3,2,1]]</strong>. <br>
    16. Set <strong>B16</strong> = the <strong>shape</strong> of B15 <br>
    17. Set <strong>B17</strong> = the <strong>2nd row</strong> of B15. <br> 
    18. Set <strong>B18</strong> = the <strong>4th column</strong> of B15. <br>
    19. Set <strong>B19</strong> = the <strong>central element</strong> in B15.<br>
</span>

In [106]:
# INSERT CODE FOR STEPS 15 - 19
import numpy as np
B15 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,12,11],[10,9,8,7,6],[5,4,3,2,1]])
B16 = B15.shape
B17 = np.array(B15[1,0:5])
B18 = np.array(B15[0:5,3])
B19 = B15[(B15.size%2+1), (B15.size%2+1)]

In [107]:
# DO NOT MODIFY !!!
print("B15:\n",B15)
print("B15 dimensions:", B16)
print("ROW 2:\n",B17)
print("COL 4:\n",B18)
print("CENTER:\n",B19)

B15:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
B15 dimensions: (5, 5)
ROW 2:
 [ 6  7  8  9 10]
COL 4:
 [ 4  9 12  7  2]
CENTER:
 13


__Review Array Shaping__

The shape of an array is the number of elements in each dimension -- this is the __shape__ attribute we looked at earlier. In NumPy, you can __reshape__ an array. Reshaping an array allows you to add or remove dimensions or change the number of elements in each dimension. A list of shape manipulation routines can be found on the NumPy API reference website: 
- https://numpy.org/doc/stable/reference/arrays.ndarray.html#shape-manipulation

w3schools.com has some good information on NumPy Array Reshaping, as well:
- https://www.w3schools.com/python/numpy_array_reshape.asp
        
Let's create an array and do some reshaping ...

__ARRAY SHAPING__

<span style="color:blue">
20. Create a <strong>NumPy</strong> array <strong>B20</strong> using <strong>arange</strong> with values <strong>1 - 16 (inclusive)</strong> and <strong>reshape</strong> it into a 2D <strong>4 x 4</strong> array. <br>
21. Create a <strong>NumPy</strong> array <strong>B21</strong> using <strong>arange</strong> with values <strong>1 - 12 (inclusive)</strong> and <strong>reshape</strong> it into a <strong>3D 2 x 3 x 2</strong> array.<br>
23. Create a <strong>2D 3 x 4 NumPy</strong> array <strong>B22</strong> with values <strong>[[1,1,1,1],[2,2,2,2],[3,3,3,3]]</strong> and <strong>reshape</strong> it into a <strong>3D 2 x 3 x 2</strong> array.<br>    
24. Create a  <strong>2D 2 x 3 NumPy</strong> array <strong>B23</strong> using with values <strong>[[1,1,1],[2,2,2]]</strong> and <strong>reshape</strong> it into a <strong>1D array</strong>.[You <strong>MUST</strong> use <strong>reshape(?)</strong> to do the "flattening". Do <strong>NOT</strong> use flatten().]<br> 
25. Create a <strong>2D 3 x 3 NumPy</strong> array <strong>B8\24</strong> using with values <strong>[[1,2,3],[4,5,6],[7,8,9]]</strong> and <strong>reshape</strong> it into a <strong>1D array</strong>.[Use the <strong>flatten()</strong> method]<br>
</span>

In [37]:
# NOTE: You can create & reshape in a single command. Ex. B = np.arange(1,5).reshape((2,2))

# INSERT CODE FOR STEPS 20 - 24
import numpy as np 
B20 = np.arange(1,17).reshape(4,4)
B21 = np.arange(1,13).reshape((2,3,2))
B22 = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]]).reshape(2,3,2)
B23 = np.array([[1,1,1],[2,2,2]]).reshape((6,))
B24 = np.array([[1,2,3],[4,5,6],[7,8,9]]).flatten()

In [38]:
# DO NOT MODIFY !!!
print("B20:\n",B20)
print("B21:\n",B21)
print("B22:\n",B22)
print("B23:\n",B23)
print("B24:\n",B24)

B20:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
B21:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
B22:
 [[[1 1]
  [1 1]
  [2 2]]

 [[2 2]
  [3 3]
  [3 3]]]
B23:
 [1 1 1 2 2 2]
B24:
 [1 2 3 4 5 6 7 8 9]


__Review Joining and Splitting__

Joining simply means putting 2 or more arrays together into a single array using the __concatenation()__ function.  A list of array manipulation routines can be found on the NumPy API reference website: 

- Joining:   https://numpy.org/doc/stable/reference/routines.array-manipulation.html#joining-arrays
- Splitting: https://numpy.org/doc/stable/reference/routines.array-manipulation.html#splitting-arrays

Here are a few joining functions:

- concatenate(...)  ~ join a sequence of arrays along an existing axis
- stack(...)        ~ join a sequence of arrays along a new axis.
- vstack(tup)       ~ stack arrays in sequence vertically (row wise).
- hstack(tup)       ~ stack arrays in sequence horizontally (column wise).
- column_stack(tup) ~ stack 1-D arrays as columns into a 2-D array.
- row_stack(tup)    ~ stack arrays in sequence vertically (row wise).

Here are a few splitting functions:

- array_split(...) ~ split an array into multiple sub-arrays.
- hsplit(...)      ~ split an array into multiple sub-arrays horizontally (column-wise).
- vsplit(...)      ~ split an array into multiple sub-arrays vertically (row-wise).

w3schools.com has some good information on NumPy Array Join & Split, as well:

- Join:  https://www.w3schools.com/python/numpy_array_join.asp
- Split: https://www.w3schools.com/python/numpy_array_split.asp

Let's do some joining and splitting ...

__ARRAY JOINING__

<span style="color:blue">
    25. Create a <strong>NumPy</strong> array <strong>B25</strong> using <strong>arange</strong> with values <strong>1 - 4 (inclusive)</strong>. <br>
    26. Create a <strong>NumPy</strong> array <strong>B26</strong> using <strong>arange</strong> with values <strong>9 - 6 (inclusive)</strong>. <br>
    27. Create array <strong>B27</strong> by <strong>concatenating</strong> arrays <strong>B26 and B25</strong>. <br>   
    28. Create array <strong>B28</strong> using <strong>vertical stacking</strong> to concatenate arrays <strong>B25 and B26</strong>. <br>
    29. Create array <strong>B29</strong> using <strong>horizonal stacking</strong> to concatenate arrays <strong>B25 with itself (B25)</strong>. <br>
    30. Create array <strong>B30</strong> using <strong>column stacking</strong> to concatenate arrays <strong>B26 and B25</strong>.
</span>

In [44]:
# INSERT CODE FOR STEPS 25 - 30
import numpy as np
B25 = np.arange(1,5)
B26 = np.arange(6,10)
B27 = np.concatenate((B25,B26))
B28 = np.stack((B25,B26))
B29 = np.hstack((B25,B25))
B30 = np.vstack((B26,B25))

In [45]:
# DO NOT MODIFY !!!
print("B25:\n",B25)
print("B26:\n",B26)
print("B27:\n",B27)
print("B28:\n",B28)
print("B29:\n",B29)
print("B30:\n",B30)

B25:
 [1 2 3 4]
B26:
 [6 7 8 9]
B27:
 [1 2 3 4 6 7 8 9]
B28:
 [[1 2 3 4]
 [6 7 8 9]]
B29:
 [1 2 3 4 1 2 3 4]
B30:
 [[6 7 8 9]
 [1 2 3 4]]


__ARRAY SPLITTING__

<span style="color:blue">
31. Create a <strong>1D NumPy</strong> array <strong>B31</strong> using <strong>arange</strong> with values <strong>1 - 9 (inclusive)</strong><br>
32. Create a <strong>NumPy</strong> array <strong>B32</strong> by splitting array <strong>B31</strong> so that there are <strong>3 elements</strong> in each subarray. <br>
33. Create a <strong>NumPy</strong> array <strong>B33</strong> with values <strong>[[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]]</strong> <br>
34. Create a <strong>NumPy</strong> array <strong>B34</strong> by splitting <strong>B33</strong> horizontally into <strong>2 2D arrays</strong>. <br>
35. Create a <strong>NumPy</strong> array <strong>B35</strong> by splitting <strong>B33</strong> vertically into <strong>2 2D arrays</strong>.   
</span>

In [46]:
# INSERT CODE FOR STEPS 31 - 35
import numpy as np
B31 = np.arange(1,10)
B32 = np.array_split(B31,3)
B33 = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])
B34 = np.hsplit(B33, 2) 
B35 = np.vsplit(B33, 2)

In [47]:
# DO NOT MODIFY !!!
print("B31:\n",B31)
print("B32:\n",B32)
print("B33:\n",B33)
print("B34:\n",B34)
print("B35:\n",B35)

B31:
 [1 2 3 4 5 6 7 8 9]
B32:
 [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
B33:
 [[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
B34:
 [array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]]), array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])]
B35:
 [array([[1, 1, 1, 1],
       [2, 2, 2, 2]]), array([[3, 3, 3, 3],
       [4, 4, 4, 4]])]


## Step C: Universal Functions (ufuncs) (12 pts)
### Add, Subtract, Multiply and Divide

__Review UFUNCS__

UFUNCS stands for "Universal Functions" which are NumPy functions that operat on the __ndarray__ object.
UFUNCS are used to implement _vectorization_ in NumPy which is faster than iterating over elements. There are over 60 univeral functions defined in NumPy, however here we will only look at a small subset -- Math operations. A list of Math-related Universal functions (ufunc) can be found on the NumPy API reference website: 
- https://numpy.org/doc/stable/reference/ufuncs.html#math-operations
        
Here are a just a few:
- add(...)      ~ add arguments element-wise
- subtract(...) ~ subtract arguments element-wise
- multiply(...) ~ multiple arguments element-wise
- divide(...)   ~ return a true division of the inputs element-wise
- mod(...)      ~ return element-wise remainder of division

Let's create an array and do some math operations  ...

<span style="color:blue">
1. Create a <strong>4 element NumPy array</strong> named <strong>C1</strong> with values <strong>[4, 8, 5, 9]</strong>. <br>
2. Create a <strong>4 element NumPy array</strong> named <strong>C2</strong> with values <strong>[7, 13, 12, 20]</strong>. <br>
3. Create a <strong>NumPy</strong> array <strong>C3</strong> by adding <strong>C1 + C2</strong>.<br>
4. Create a <strong>NumPy</strong> array <strong>C4</strong> by subtracting <strong>C1 - C2</strong>.<br>   
5. Create a <strong>NumPy</strong> array <strong>C5</strong> by multiplying <strong>C1 x C2 </strong>.<br>
6. Create a <strong>NumPy</strong> array <strong>C6</strong> by getting the remainder of <strong>C2 / C1</strong>
</span>

In [53]:
# INSERT CODE FOR STEPS 1 - 6
import numpy as np
C1 = np.array([4, 8, 5, 9])
C2 = np.array([7,13,12,20])
C3 = np.add(C1, C2)
C4 = np.subtract(C1,C2)
C5 = np.multiply(C1,C2)
C6 = np.mod(C2,C1)

In [54]:
# DO NOT MODIFY !!!
print("C1:\n",C1)
print("C2:\n",C2)
print("C3:\n",C3)
print("C4:\n",C4)
print("C5:\n",C5)
print("C6:\n",C6)

C1:
 [4 8 5 9]
C2:
 [ 7 13 12 20]
C3:
 [11 21 17 29]
C4:
 [ -3  -5  -7 -11]
C5:
 [ 28 104  60 180]
C6:
 [3 5 2 2]


## Step D: Statistics (8 pts)

__Review Statistics Functions__

NumPy is used quite a bit for statistics, so let's take a look at some of the many statistics functions available. A list of Statistics functions can be found on the NumPy API reference website: 
- https://numpy.org/doc/stable/reference/routines.statistics.html
        
Here are just a few:
- amin(...)    ~ return the minimum of an array or minimum along an axis.
- amax(...)    ~ return the maximum of an array or maximum along an axis.
- median(...)  ~ compute the median along the specified axis.
- average(...) ~ compute the weighted average along the specified axis.
- mean(...)    ~ compute the arithmetic mean along the specified axis.
- std(...)     ~ compute the standard deviation along the specified axis.
- var(...)     ~ Compute the variance along the specified axis.

Let's create an array and do some statistical operations  ...

__MINIMUM, MAXIMUM, AVERAGE, MEAN, STD DEV and VAR__

<span style="color:blue">
    1. Create a <strong>NumPy</strong> array <strong>D1</strong> using <strong>array</strong> using the list of values <strong>[2,7,90,-1,-6,33,0,4]</strong> <br>
    2. Set <strong>D2</strong> = the <strong>minimum value</strong> in <strong>D1</strong>.<br>  
    3. Set <strong>D3</strong> =  the <strong>maximum value</strong> in <strong>D1</strong>.<br> 
    4. Set <strong>D4</strong> =  the <strong>median value</strong> of <strong>D1</strong>.<br>
    5. Set <strong>D5</strong> =  the <strong>average value</strong> of <strong>D1</strong>.<br>
    6. Set <strong>D6</strong> =  the <strong>mean value</strong> in <strong>D1</strong>.<br>
    7. Set <strong>D7</strong> =  the <strong>standard deviation</strong> of the values in <strong>D1</strong>.<br>
    8. Set <strong>D8</strong> =  the <strong>variance</strong> of the values in <strong>D1</strong>.
</span>

In [57]:
# INSERT CODE FOR STEPS 1 - 7
import numpy as np
D1 = np.array([2,7,90,-1,-6,33,0,4])
D2 = np.amin(D1)
D3 = np.amax(D1)
D4 = np.median(D1)
D5 = np.average(D1)
D6 = np.mean(D1)
D7 = np.std(D1)
D8 = np.var(D1)

In [58]:
# DO NOT MODIFY !!!
print("D1: ",D1)
print("MIN: ",D2)
print("MAX: ",D3)
print("MEDIAN: ",D4)
print("AVERAGE: ",D5)
print("MEAN: ", D6)
print("STD DEV: ",D7)
print("VARIANCE:", D8)

D1:  [ 2  7 90 -1 -6 33  0  4]
MIN:  -6
MAX:  90
MEDIAN:  3.0
AVERAGE:  16.125
MEAN:  16.125
STD DEV:  30.030973593941305
VARIANCE: 901.859375


In [24]:
print("THE END!")

THE END!
