# Lab 5: Pandas Introduction

### Author: <font color='red'> Charles Moore </font>

## Verify installation of Pandas

In [1]:
# Verify Pandas libraries are installed
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

# Display version information
print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version: 1.20.1
Pandas version: 1.2.4


In [2]:
# Import two more Python libraries ...
import csv
import os

### Display Pandas Series Help Documentation

In [3]:
# Adding a ? will generate in-line help for a command
# Run this cell to see the output generated for Pandas Series
#pd.Series?

<div class="alert alert-block alert-warning">
<b>COMMENT OUT the pd.Series? HELP Command above:</b> <br>
Running the Help '?' commands was for informational purposes only.<br>
<b>Comment out the line above and rerun the cell to remove the generated output.</b></div>

### Display Panda Dataframe Help Documentation

In [5]:
# Adding a ? will generate in-line help for a command
# Run this cell to see the output generated for Pandas Dataframe
#pd.DataFrame?

<div class="alert alert-block alert-warning">
<b>COMMENT OUT the p.DataFrame? HELP Command above:</b> <br>
Running the Help '?' commands was for informational purposes only.<br>
<b>Comment out the line above and rerun the cell to remove the generated output.</b></div>

## PART A: Pandas Series (30 pts)
### Creating Pandas Series

The base data structure of Pandas is the __Series object__. It is a one-dimensional array, similar to a NumPy array, but also has special index capabilities. Think of a series as a column in a table, a one-dimensional array that can hold data of any type. Unlike a standard array, a Series object can have labels. If no labels are defined, the default is to use the index numbers.

A simple way to create a Series object is by initializing a Series object using a Python array, Python __list__, or a Python __dictionary__ 

__ADDITIONAL REFERENCES & EXAMPLES__

w3schools.com site (Pandas Series creation examples)

    REF: https://www.w3schools.com/python/pandas_series.asp
    
pandas.pydata.org site (information about Pandas Series attributes):

    REF: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html
    
Here are a few commonly used attributes of a Series:

__ATTRIBUTES__

- nbytes ~ Return the number of bytes in the underlying data.
- ndim   ~ Number of dimensions of the underlying data, by definition 1.
- shape  ~ Return a tuple of the shape of the underlying data.
- size   ~ Return the number of elements in the underlying data.
- values ~ Return Series as ndarray or ndarray-like depending on the dtype.

Let's try a few ...

Create a Series using a Python List:
<span style="color:blue">
1. Create a Pandas <strong>Series</strong> named <strong>S1</strong> from a <strong>Python list</strong> containing different data types <strong>[9, 5.1, 'WTCC', 'CSC221', 2021]</strong>. <br>
2.Set variable <strong>V1</strong> to the values of <strong>S1</strong> <br>
3.Set variable <strong>V2</strong> to the number of bytes in <strong>S1</strong> <br>    
4.Set variable <strong>V3</strong> to the number of dimensions of <strong>S1</strong> <br>
5.Set variable <strong>V4</strong> to the shape of <strong>S1</strong> <br>
6.Set variable <strong>V5</strong> to the size of <strong>S1</strong> <br>
</span>

In [34]:
# INSERT CODE FOR STEPS 1 - 6
import pandas as pd

S1 = pd.Series([9, 5.1, 'WTCC', 'CSC221', 2021])
V1 = S1.values
V2 = S1.nbytes
V3 = S1.ndim
V4 = S1.shape
V5 = S1.size


In [35]:
# DO NOT MODIFY !!!

# Print the Series values 
print("V1:", V1)
# Print the Series attributes
print("V2:", V2)
print("V3:", V3)
print("V4:", V4)
print("V5:", V5)

V1: [9 5.1 'WTCC' 'CSC221' 2021]
V2: 40
V3: 1
V4: (5,)
V5: 5


__SERIES CREATION__

As mentioned above, although the most common way to create a Series is using a Python __List__, you can also create a Series object using a Python __dictionary__ {key:value,key:value,...}. The __keys__ become the labels.

__NOTE the difference between the two -- specifically the first column -- the index__

Create a Series using a Python List and a Python Dictionary:

<span style="color:blue">
7. Create a Pandas <strong>Series</strong> named <strong>S2_LIST</strong> using a <strong>Python list</strong> containing <strong>[31,28,31,30,31]</strong>. <br>
8. Create a Pandas <strong>Series</strong> named <strong>S2_DICT</strong> using a <strong>Python dictionary</strong> containing <strong>{'Jan': 31, 'Feb': 28, 'Mar': 31, 'Apr': 30, 'May': 31}</strong>
</span>

In [36]:
# INSERT CODE FOR STEPS 7 - 8
import pandas as pd
S2_LIST = pd.Series([31,28,31,30,31])
S2_DICT = pd.Series({'Jan': 31, 'Feb': 28, 'Mar': 31, 'Apr': 30, 'May': 31})

In [37]:
# DO NOT MODIFY !!!
print("S2_LIST\n", S2_LIST, sep='')
print()
print("S2_DICT\n", S2_DICT, sep='') 

S2_LIST
0    31
1    28
2    31
3    30
4    31
dtype: int64

S2_DICT
Jan    31
Feb    28
Mar    31
Apr    30
May    31
dtype: int64


__NOTE:__ Printing a Pandas Series results in __two columns__ of output. 

The first column is __not__ Series data; it is __index__ labels. The second column contains the __values__ of the Series object. Each row represents the index label and the value for that label.

If a Series is created __without__ specifying an explicit index, Pandas automatically creates a __0-based implicit index__, as with lists and NumPy arrays. Elements of a Series object can be accessed through the index using regular indexing brackets: [].

If a Series is created with a __user-defined index__ (i.e. labels) using a Python __dictionary__ OR using the __index=__ parameter, elements of a Series object can be accessed using EITHER the _alphanumeric index labels or the 0-based implicit index_.

__INDEXES__


<span style="color:blue">
    9. Create a new <strong>Series</strong> named <strong>S3</strong> using an <strong>explicit index</strong>. Use a the list <strong>['stop', 'yield', 'go']</strong> and an index of <strong>['red','yellow','green]</strong>. <br>
    10.Set variable <strong>V10</strong> to the values of <strong>S3</strong> <br>
    11.Set variable <strong>V11</strong> to the index values of <strong>S3</strong> <br>    
    12.Set variable <strong>V12</strong> to the value associated with index <strong>'yellow'</strong> <br>
    13.Set variable <strong>V13</strong> to the values associated with index <strong>'red' and 'green'</strong> <br>
</span>

In [38]:
# INSERT CODE FOR STEPS 9 - 13
import pandas as pd
S3 = pd.Series(['stop', 'yield', 'go'] , index = ['red','yellow','green'])
V10 = S3
V11 = S3.index
V12 = S3['yellow']
V13 = S3[['red','green']]

In [39]:
# DO NOT MODIFY !!!
# Print the Series values 
print("V10 Series:\n", V10, sep='')
# Print the Series index values
print("\nV11:", V11)
# Print specific index values
print("\nV12:", V12)
print("\nV13:\n", V13, sep='')

V10 Series:
red        stop
yellow    yield
green        go
dtype: object

V11: Index(['red', 'yellow', 'green'], dtype='object')

V12: yield

V13:
red      stop
green      go
dtype: object


<span style="color:blue">
    14.Update the value associated with index <strong>'green'</strong> to <strong>'hurry up'</strong> <br> 
    15.Set variable <strong>V14</strong> to updated values of <strong>S3</strong> <br>
    16.Set variable <strong>V15</strong> to the value <strong>'yield'</strong> BUT use the 0-based index (NOT the label!)
</span>

In [40]:
# INSERT CODE FOR STEPS 14 -16
S3['green'] = 'hurry up'
V14 = S3
V15 = S3[1]

In [41]:
# DO NOT MODIFY !!!
# Print updated Series values
print("V14 Series\n", V14, sep='')
print()
# Print specific 0-based index value
print("V15:", V15)

V14 Series
red           stop
yellow       yield
green     hurry up
dtype: object

V15: yield


__DATETIMEINDEX__ 

A common usage for a Series is to represent a __time series__ that associates date/time index labels with values. 

A date range can be created using the Pandas method __pd.date_range()__.

    REF: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.date_range.html

A data range index in Pandas is referred to as a __DatetimeIndex__, which is a Pandas index optimized to index data with dates and times.

    REF: https://pandas.pydata.org/docs/reference/api/pandas.DatetimeIndex.html

Let's create a one ...

<span style="color:blue">
17. Use the <strong>pd.date_range(...)</strong> command to create a <strong>DatetimeIndex</strong> named <strong>INDEX_DATES</strong> with indices between <strong>'2016-11-01'</strong> and <strong>'2016-11-08'</strong> <br>
18. Create a <strong>Series</strong> named <strong>S4_TEMPS</strong> with temperature values <strong>[60, 62, 65, 70, 63, 67, 65, 66]</strong> and <strong>dates for the index</strong> <br>
</span>

In [42]:
# INSERT CODE FOR STEPS 17 - 18
INDEX_DATES = pd.date_range('2016-11-01','2016-11-08' )
S4_TEMPS = pd.Series([60, 62, 65, 70, 63, 67, 65, 66],index=INDEX_DATES)

In [43]:
# DO NOT MODIFY !!!
print("INDEX_DATES:\n", INDEX_DATES, sep='')
print("S4_TEMPS:\n", S4_TEMPS, sep='' )

INDEX_DATES:
DatetimeIndex(['2016-11-01', '2016-11-02', '2016-11-03', '2016-11-04',
               '2016-11-05', '2016-11-06', '2016-11-07', '2016-11-08'],
              dtype='datetime64[ns]', freq='D')
S4_TEMPS:
2016-11-01    60
2016-11-02    62
2016-11-03    65
2016-11-04    70
2016-11-05    63
2016-11-06    67
2016-11-07    65
2016-11-08    66
Freq: D, dtype: int64


__STATISTICAL METHODS__

Statistical methods provided by NumPy can be applied to a Pandas Series -- including mean, median, standard deviation, etc.

    REF: https://pandas.pydata.org/pandas-docs/stable/reference/series.html#computations-descriptive-stats

Here are just a few:

- Series.max(...)    ~ Return the maximum of the values over the requested axis.
- Series.mean(...)   ~ Return the mean of the values over the requested axis.
- Series.median(...) ~ Return the median of the values over the requested axis.
- Series.min(...)    ~ Return the minimum of the values over the requested axis.
- Series.std(...)    ~ Return sample standard deviation over requested axis.
- Series.sum(...)    ~ Return the sum of the values over the requested axis.
- Series.var(...)    ~ Return unbiased variance over requested axis.

Let's try a few using the Series created above (__S4_TEMPS__)

<span style="color:blue">
    19.Set variable <strong>V19</strong> to the <strong>mean</strong> value of <strong>S4_TEMPS</strong> <br>
    20.Set variable <strong>V20</strong> to the <strong>max</strong> value of <strong>S4_TEMPS</strong> <br> 
    21.Set variable <strong>V21</strong> to the <strong>min</strong> value of <strong>S4_TEMPS</strong> <br> 
    22.Set variable <strong>V22</strong> to the <strong>median</strong> value of <strong>S4_TEMPS</strong> <br> 
    23.Set variable <strong>V23</strong> to the <strong>sum</strong> value of <strong>S4_TEMPS</strong> <br> 
    24.Set variable <strong>V24</strong> to the <strong>standard deviation</strong> value of <strong>S4_TEMPS</strong>
</span>

In [44]:
# INSERT CODE FOR STEPS 19 - 24
V19 = S4_TEMPS.mean()
V20 = S4_TEMPS.max()
V21 = S4_TEMPS.min()
V22 = S4_TEMPS.median()
V23 = S4_TEMPS.sum()
V24 = S4_TEMPS.std()

In [45]:
# DO NOT MODIFY !!!
print("S4_TEMPS mean:", V19)
print("S4_TEMPS max:", V20)
print("S4_TEMPS min:", V21)
print("S4_TEMPS median:", V22)
print("S4_TEMPS sum:", V23)
print("S4_TEMPS std:", V24)

S4_TEMPS mean: 64.75
S4_TEMPS max: 70
S4_TEMPS min: 60
S4_TEMPS median: 65.0
S4_TEMPS sum: 518
S4_TEMPS std: 3.1052950170405937


__ADDITION / SUBTRACTION__

__NOTE:__ You can __add (+)__ and __subtract (-)__ Series values as well, give it a try ...

<span style="color:blue">
    25. Create a new <strong>Series</strong> named <strong>S5_TEMPS</strong> with temperature values <strong>[70, 75, 69, 73, 79, 77, 74, 72]</strong> and <strong>INDEX_DATES</strong> for the index <br>
    26. Create a <strong>Series</strong> named <strong>TEMP_DIFFS1</strong> with temperature <strong>differences</strong> between <strong>S4_TEMPS</strong> and <strong>S5_TEMPS</strong> (subtract S4_TEMPS from S5_TEMPS) <br>
    27. Create a <strong>Series</strong> named <strong>TEMP_DIFFS2</strong> with temperature <strong>differences</strong> between <strong>S5_TEMPS</strong> and <strong>S4_TEMPS</strong> (subtract S5_TEMPS from S4_TEMPS) <br>
    28. Create a <strong>Series</strong> named <strong>TEMP_SUMS</strong> with temperature <strong>sum</strong> of <strong>S4_TEMPS</strong> and <strong>S5_TEMPS</strong> <br>
    29. Create a <strong>Series</strong> named <strong>TEMP_PLUS10</strong> by adding <strong>10</strong> to the temperature of <strong>S4_TEMPS</strong> <br>
    30. Create a <strong>Series</strong> named <strong>TEMP_MINUS10</strong> by subtracting <strong>10</strong> from the temperature of <strong>S5_TEMPS</strong>
</span>

In [46]:
# INSERT CODE FOR STEPS 25 - 30
S5_TEMPS = pd.Series([70, 75, 69, 73, 79, 77, 74, 72], index = INDEX_DATES)
TEMP_DIFFS1 = S4_TEMPS-S5_TEMPS
TEMP_DIFFS2 = S5_TEMPS-S4_TEMPS
TEMP_SUMS = S4_TEMPS+S5_TEMPS
TEMP_PLUS10 = S4_TEMPS+10
TEMP_MINUS10 = S5_TEMPS-10

In [47]:
# DO NOT MODIFY !!!
print("S4_TEMPS:\n",S4_TEMPS.values)
print("S5_TEMPS:\n",S5_TEMPS.values)
print("TEMP_DIFFS1:\n",TEMP_DIFFS1.values)
print("TEMP_DIFFS2:\n",TEMP_DIFFS2.values)
print("TEMP_SUMS:\n",TEMP_SUMS.values)
print("TEMP_PLUS10:\n",TEMP_PLUS10.values)
print("TEMP_MINUS10:\n",TEMP_MINUS10.values)

S4_TEMPS:
 [60 62 65 70 63 67 65 66]
S5_TEMPS:
 [70 75 69 73 79 77 74 72]
TEMP_DIFFS1:
 [-10 -13  -4  -3 -16 -10  -9  -6]
TEMP_DIFFS2:
 [10 13  4  3 16 10  9  6]
TEMP_SUMS:
 [130 137 134 143 142 144 139 138]
TEMP_PLUS10:
 [70 72 75 80 73 77 75 76]
TEMP_MINUS10:
 [60 65 59 63 69 67 64 62]


## PART B: DataFrame Object: (40 pts - 2pts/each)

If you want to have more than one **Series** of data that is _aligned by a common index_, then a Pandas **DataFrame** is used. A **DataFrame** is like a database table, where **each column** has the same type of data, but the columns can have different types of data. Columns in a **DataFrame** object can be accessed using an array indexer [] with the name of the column or a list of column names.


There is an indexing difference between **DataFrame** objects and **Series** objects. If you pass a **list** to the **indexing [] operator** of a **DataFrame**, it retrieves the specified **columns**, whereas a **Series** uses the list as index labels to retrieve rows. 

So, with a **DataFrame** object, if the name of a column *does not have spaces*, you can **use the column name** to access the column of data in a **DataFrame** (i.e. 'dot' syntax), for example: __TEMPDF.Atlanta__ instead of __TEMPDF['Atlanta']__

__DATAFRAME CREATION__

<span style="color:blue">
    1. Create a <strong>DataFrame</strong> object named <strong>DF1</strong> with <strong>two columns</strong> representing the temperatures from the two Series objects created earlier, <strong>S4_TEMPS</strong> and <strong>S5_TEMPS</strong>. Give them <strong>city column names</strong> of <strong>'Raleigh'</strong> and <strong>'Charlotte'</strong>. (in the order given: S4_TEMPS for Raleigh; S5_TEMPS for Charlotte)<br>
    2.Set variable <strong>V25</strong> to the column of <strong>DF1</strong> with the name <strong>'Raleigh'</strong> <br>
    3.Set variable <strong>V26</strong> to the column of <strong>DF1</strong> with the name <strong>'Charlotte'</strong> -<strong>use the column name</strong> 'dot' syntax <br>
    4.Create <strong>DF1_REV</strong> containing both columns in <strong>DF1</strong> in the <strong>reverse order</strong> [Charlotte column 1st and Raleigh column 2nd] <br>
</span>

In [48]:
# INSERT CODE FOR STEPS 1 - 4
DF1 = pd.DataFrame(columns = ['Raleigh','Charlotte'])
DF1['Raleigh'] = S4_TEMPS
DF1['Charlotte'] = S5_TEMPS
V25 = DF1['Raleigh']
V26 = DF1.Charlotte
DF1_REV = pd.DataFrame(columns = ['Charlotte','Raleigh'])
DF1_REV['Charlotte'] = S5_TEMPS
DF1_REV['Raleigh'] = S4_TEMPS

In [49]:
# DO NOT MODIFY !!!
print("\nDATAFRAME DF1\n", DF1)
print("\nV25\n", V25, sep='')
print("\nV26\n", V26, sep='')
print("\nDATAFRAME DF1_REV\n", DF1_REV)


DATAFRAME DF1
             Raleigh  Charlotte
2016-11-01       60         70
2016-11-02       62         75
2016-11-03       65         69
2016-11-04       70         73
2016-11-05       63         79
2016-11-06       67         77
2016-11-07       65         74
2016-11-08       66         72

V25
2016-11-01    60
2016-11-02    62
2016-11-03    65
2016-11-04    70
2016-11-05    63
2016-11-06    67
2016-11-07    65
2016-11-08    66
Freq: D, Name: Raleigh, dtype: int64

V26
2016-11-01    70
2016-11-02    75
2016-11-03    69
2016-11-04    73
2016-11-05    79
2016-11-06    77
2016-11-07    74
2016-11-08    72
Freq: D, Name: Charlotte, dtype: int64

DATAFRAME DF1_REV
             Charlotte  Raleigh
2016-11-01         70       60
2016-11-02         75       62
2016-11-03         69       65
2016-11-04         73       70
2016-11-05         79       63
2016-11-06         77       67
2016-11-07         74       65
2016-11-08         72       66


__ARITHMETIC OPERATIONS__

Arithmetic operations between columns within a __DataFrame__ are identical to operations on multiple __Series__.
Each column in a __DataFrame__ is a __Series__ so the use of mathematical operators is applicable. Ex: [+ - * /  // % **]

__NOTE:__ You can also add new columns to a __DataFrame__ using the syntax:

    <DataFrame>['columnheading'] = <DataFrame-to-Add>
 
Let's do a little DataFrame arithmetic ... 

<span style="color:blue">
5. Calculate the <strong>temperature difference</strong> between the two cities [subtract Charlotte from Raleigh] and save the results in <strong>DF1_DIFF</strong><br>
6. Calculate the <strong>Raleigh</strong> temperatures in <strong>Celcius ((F -32) * 5) / 9)</strong> and save the results in <strong>DF1_RAL_TEMPC</strong> <br>
7. Calculate the <strong>Charlotte</strong> temperatures in <strong>Celcius ((F -32) * 5) / 9)</strong> and save the results in <strong>DF1_CLT_TEMPC</strong> <br>    
8. Add a new column with the <strong>DF1_DIFF</strong> values to the <strong>DF1</strong> DataFrame with the column heading <strong>'Diff'</strong>. <br>
9. Add a new column with the <strong>DF1_RAL_TEMPC</strong> values to the <strong>DF1</strong> DataFrame with the column heading <strong>'Ral-C'</strong>. <br>
10. Add a column with the <strong>DF1_CLT_TEMPC</strong> values to the <strong>DF1</strong> DataFrame with the column heading <strong>'Clt-C'</strong>. <br> 
</span>

In [67]:
# INSERT CODE FOR STEPS 5 - 10
DF1_DIFF = DF1.Raleigh-DF1.Charlotte
DF1_RAL_TEMPC = (((DF1.Raleigh-32)*5)/9)
DF1_CLT_TEMPC = (((DF1.Charlotte-32)*5)/9)
DF1['Diff'] = DF1_DIFF
DF1['Ral-C'] = DF1_RAL_TEMPC
DF1['Clt-C'] = DF1_CLT_TEMPC

In [68]:
# DO NOT MODIFY !!!

# Print the temperature difference between the two cities
print("DF1_DIFF DataFrame\n", DF1_DIFF, sep='')

# Print the Raleigh temperatures in Celcius 
print("\nDF1_RAL_TEMPC DataFrame\n", DF1_RAL_TEMPC, sep='')

# Print the Charlotte temperatures in Celcium
print("\nDF1_CLT_TEMPC DataFrame\n", DF1_CLT_TEMPC, sep='')

# Print DF1 with 3 new columns
print("\nDF1 DataFrame\n", DF1)

DF1_DIFF DataFrame
2016-11-01   -10
2016-11-02   -13
2016-11-03    -4
2016-11-04    -3
2016-11-05   -16
2016-11-06   -10
2016-11-07    -9
2016-11-08    -6
Freq: D, dtype: int64

DF1_RAL_TEMPC DataFrame
2016-11-01    15.555556
2016-11-02    16.666667
2016-11-03    18.333333
2016-11-04    21.111111
2016-11-05    17.222222
2016-11-06    19.444444
2016-11-07    18.333333
2016-11-08    18.888889
Freq: D, Name: Raleigh, dtype: float64

DF1_CLT_TEMPC DataFrame
2016-11-01    21.111111
2016-11-02    23.888889
2016-11-03    20.555556
2016-11-04    22.777778
2016-11-05    26.111111
2016-11-06    25.000000
2016-11-07    23.333333
2016-11-08    22.222222
Freq: D, Name: Charlotte, dtype: float64

DF1 DataFrame
             Raleigh  Charlotte  Diff      Ral-C      Clt-C
2016-11-01       60         70   -10  15.555556  21.111111
2016-11-02       62         75   -13  16.666667  23.888889
2016-11-03       65         69    -4  18.333333  20.555556
2016-11-04       70         73    -3  21.111111  22.77777

The names of columns in a __DataFrame__ object are accessible via the __DataFrame__ object's __columns property__, which itself is a __Pandas Index__ object. 

In addition, the __DataFrame__ object can be accessed as a __NumPy array__ by using its __values attribute__. 

    REF: https://pandas.pydata.org/pandas-docs/stable/reference/frame.html

__SOME DATAFRAME ATTRIBUTES__

- DataFrame.index     ~ The index (row labels) of the DataFrame.
- DataFrame.columns   ~ The column labels of the DataFrame.
- DataFrame.dtypes    ~  Return the dtypes in the DataFrame.
- DataFrame.info(...) ~ Print a concise summary of a DataFrame.
- DataFrame.values    ~ Return a Numpy representation of the DataFrame.
- DataFrame.axes      ~ Return a list representing the axes of the DataFrame.
- DataFrame.ndim      ~ Return an int representing the number of axes / array dimensions.
- DataFrame.size      ~ Return an int representing the number of elements in this object.
- DataFrame.shape     ~ Return a tuple representing the dimensionality of the DataFrame.

Let's check out a few of these ...

<span style="color:blue">
    11.Set variable <strong>V27</strong> to the columns labels of <strong>DF1</strong><br>
    12.Set variable <strong>V28</strong> to the NumPy representation of <strong>DF1</strong> <br>
    13.Set variable <strong>V29</strong> to the shape of <strong>DF1</strong> <br>
    14.Set variable <strong>V30</strong> to the size of <strong>DF1</strong>
</span>

In [69]:
# INSERT CODE FOR STEPS 11 - 14
V27 = DF1.columns
V28 = DF1.values
V29 = DF1.shape
V30 = DF1.size


In [70]:
# Print the column labels of DF1
print("DF1 columns:\n",V27)
print("\nDF1 values:\n", V28, sep='')
print("\nDF1 shape:", V29)
print("\nDF1 size:", V30)

DF1 columns:
 Index(['Raleigh', 'Charlotte', 'Diff', 'Ral-C', 'Clt-C'], dtype='object')

DF1 values:
[[ 60.          70.         -10.          15.55555556  21.11111111]
 [ 62.          75.         -13.          16.66666667  23.88888889]
 [ 65.          69.          -4.          18.33333333  20.55555556]
 [ 70.          73.          -3.          21.11111111  22.77777778]
 [ 63.          79.         -16.          17.22222222  26.11111111]
 [ 67.          77.         -10.          19.44444444  25.        ]
 [ 65.          74.          -9.          18.33333333  23.33333333]
 [ 66.          72.          -6.          18.88888889  22.22222222]]

DF1 shape: (8, 5)

DF1 size: 40


__DATAFRAME INDEXING__

The __DataFrame__ objects can be __sliced__ to retrieve specific rows using __implicit indexing__. <br>
Entire rows from a __DataFrame__ can be retrieved using:

        - <DataFrame>.loc    ~ explicit indexing
            - Access a group of rows and columns by label(s) or a boolean array.
        - <DataFrame>.iloc   ~ implicit indexing
            -Purely integer-location based indexing for selection by position.
        
Specific rows in a __DataFrame__ object can also be selected using:
        - A __list__ of integer positions (Ex. [1,5,7]) 
        - A __logical expression__ applied to the data in each row (Ex. < > <= >= == ) 

    REF: https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#indexing-iteration


Let's use these index methods to retrieve various rows ...

<span style="color:blue">
    15.Set variable <strong>V31</strong> to <strong>DF1</strong> column <strong>'Diff'</strong> rows with <strong>implicit index locations 2 through 4</strong><br>
    16.Set variable <strong>V32</strong> to <strong>DF1</strong> rows with dates <strong>‘2016-11-03’, ‘2016-11-04’ and ‘2016-11-05’</strong> using slicing on the <strong>explicit row index</strong><br>
    17.Set variable <strong>V33</strong> to <strong>DF1</strong> row with <strong>implicit index position 1</strong> (second row)<br>
    18.Set variable <strong>V34</strong> to <strong>DF1</strong> row with date <strong>'2016-11-04'</strong> using <strong>.loc</strong><br>
    19.Set variable <strong>V35</strong> to <strong>DF1</strong> column <strong>'Charlotte'</strong> rows with <strong>implicit indices 2, 5, and 7</strong> (0-based location). <br>
    20.Set variable <strong>V36</strong> to <strong>DF1</strong> days where the temperature in <strong>'Raleigh'</strong> is <strong>above 65. <br>
</span>

In [83]:
#### INSERT CODE FOR STEPS 15 - 20
V31 = DF1['Diff'].iloc[2:5]
V32 = DF1.loc['2016-11-03':'2016-11-05']
V33 = DF1.iloc[1]
V34 = DF1.loc['2016-11-04']
V35 = DF1['Charlotte'].iloc[[2,5,7]]
V36 = DF1.loc[DF1['Raleigh'] > 65]

In [84]:
# DO NOT MODIFY !!!
print("DF1 Diff Column Rows 2-4:\n", V31, sep='')
print("\nDF1 Rows for Nov 3-5:\n", V32, sep='')
print("\nDF1 Second Row:\n", V33, sep='')
print("\nDF1 Row for Nov 4:\n", V34, sep='')
print("\nDF1 Charlotte Rows 2,5,7:\n", V35, sep='')
print("\nDF1 Raleigh temp>65:\n", V36, sep='')

DF1 Diff Column Rows 2-4:
2016-11-03    -4
2016-11-04    -3
2016-11-05   -16
Freq: D, Name: Diff, dtype: int64

DF1 Rows for Nov 3-5:
            Raleigh  Charlotte  Diff      Ral-C      Clt-C
2016-11-03       65         69    -4  18.333333  20.555556
2016-11-04       70         73    -3  21.111111  22.777778
2016-11-05       63         79   -16  17.222222  26.111111

DF1 Second Row:
Raleigh      62.000000
Charlotte    75.000000
Diff        -13.000000
Ral-C        16.666667
Clt-C        23.888889
Name: 2016-11-02 00:00:00, dtype: float64

DF1 Row for Nov 4:
Raleigh      70.000000
Charlotte    73.000000
Diff         -3.000000
Ral-C        21.111111
Clt-C        22.777778
Name: 2016-11-04 00:00:00, dtype: float64

DF1 Charlotte Rows 2,5,7:
2016-11-03    69
2016-11-06    77
2016-11-08    72
Name: Charlotte, dtype: int64

DF1 Raleigh temp>65:
            Raleigh  Charlotte  Diff      Ral-C      Clt-C
2016-11-04       70         73    -3  21.111111  22.777778
2016-11-06       67         77 

## PART C: Pandas with Stock CSV Dataset: (30 pts - 2 pts/each)

<div class="alert alert-block alert-info">
    <b>INFORMATION:</b> In PART C, you will be using <b>Pandas</b> to compute various statistics.<br> 
    A dataset (CSV-files) is provided with the lab assignment. This dataset will be read into a <b>DataFrame<b>.<br><br>
    - 4stocks_1qtr.csv ~ stock info for 1st quarter of 2017

</div>

<span style="color:blue">
Verify your <strong>current working directory</strong> using <strong>getcwd()</strong>. Your stock CSV files <strong>MUST</strong> be located in the directory displayed as CWD.<br>
</span>

In [85]:
# Display your current working directory
# IMPORTANT: Your CSV files must be located in this directory
# If the stock CSV files for this lab are not in this directory you MUST move
# the files to this location before you can continue!
import os
print(os.getcwd())

/home/chad/_CSC221/Lab 4


### Reading CSV files

A common data format for storing and sharing data is a __CSV__ file (i.e command separated value). __Pandas__ has a __read_csv()__ function making it quite simple to import such files.

__ADDITIONAL REFERENCES & EXAMPLES__
    
pandas.pydata.org site (information about Pandas read_csv() function):

    REF: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html
    
w3schools.com site (Pandas Read CSV examples)    

    REF: https://www.w3schools.com/python/pandas_csv.asp

__Take a look first !__

Before analyzing the data read into a DataFrame, you'll often want to take a quick look at the data. 

- To print all the data in a DataFrame, you can use __to_string()__. EXAMPLE: __print(df.to_string())__

        REF: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_string.html
    

- To print just a subset of the DataFrame, you can use __head()__ and/or __tail()__. If no value is specified, a __default = 5__ is used.

pandas.pydata.org site (information about head() and tail() functions):

    REF: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html
    
    REF: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.tail.html
    
EXAMPLES:<br>
__head()__ ~ display first 5 rows <br>
__head(10)__ ~ display first 10 rows <br>
__tail()__ ~ display last 5 rows <br>
__head(10)__ ~ display last 10 rows <br>


<span style="color:blue">
    1. Create variable <strong>cols</strong> as a <strong>list</strong> of column headings for the stocks dataset (1st Qtr 2017). <br>&nbsp; &nbsp; &nbsp; &nbsp; Set the headings to <strong>['Date','Open','High','Low','Close','Volume','Name']</strong> <br> 
    2. Use <strong>pd.read_csv</strong> to read the stocks data file for 1st quarter 2017 <strong>(4stocks_1qtr.csv)</strong> into <strong>STOCKS_DF1</strong> using the column headings defined by <strong>cols</strong><br>&nbsp; &nbsp; &nbsp; &nbsp; To set the collumn headings, you will need to use the <strong>names = </strong> parameter <br> 
    3. Set variable <strong>STOCKS_DF1_FIRST6</strong> to the first <strong>6</strong> records of the DataFrame <strong>STOCKS_DF1</strong> using the <strong>head()</strong> function.
</span>

In [162]:
# INSERT CODE FOR STEPS 1 - 3
cols = ['Date','Open','High','Low','Close','Volume','Name'] 
STOCKS_DF1 = pd.read_csv('4stocks_1qtr.csv',names = cols)

STOCKS_DF1_FIRST6 = STOCKS_DF1.head(6)

In [104]:
# DO NOT MODIFY !!!
STOCKS_DF1_FIRST6

Date    Open    High     Low   Close    Volume  Name
0   1/3/2017  115.80  116.33  114.76  116.15  28781865  AAPL
1   1/4/2017  115.85  116.51  115.75  116.02  21118116  AAPL
2   1/5/2017  115.92  116.86  115.81  116.61  22193587  AAPL
3   1/6/2017  116.78  118.16  116.47  117.91  31751900  AAPL
4   1/9/2017  117.95  119.43  117.94  118.99  33561948  AAPL
5  1/10/2017  118.77  119.38  118.30  119.11  24462051  AAPL

<span style="color:blue">
    4. Set variable <strong>STOCKS_DF1_TYPE</strong> to the <strong>data types</strong> Pandas assigned to <strong>STOCKS_DF1</strong> (Use dtype)
</span>

In [105]:
# INSERT CODE FOR STEP 4
STOCKS_DF1_TYPE = STOCKS_DF1.dtypes

In [106]:
# DO NOT MODIFY !!!
STOCKS_DF1_TYPE

Date       object
Open      float64
High      float64
Low       float64
Close     float64
Volume      int64
Name       object
dtype: object

<span style="color:blue">
    5. Set variable <strong>STOCKS_DF1_SHAPE</strong> to the number of rows and columns <strong>STOCKS_DF1</strong> (Use shape)
</span>

In [107]:
# INSERT CODE FOR STEP 5
STOCKS_DF1_SHAPE = STOCKS_DF1.shape

In [108]:
# DO NOT MODIFY !!!
STOCKS_DF1_SHAPE

(248, 7)

<span style="color:blue">
    6. Create a new column for <strong>STOCKS_DF1 DataFrame</strong> called <strong>'Year'</strong> that contains the year extracted from the <strong>Date</strong> column using a <strong>simple vectorized string opteration</strong> <br>
<ul>
    <li>Reference PART B in this Lab for how to add a new column to a DataFrame. </li>
    <li>The new column will be named <strong>'Month'</strong> </li>
    <li>Use 'Date' as the column and .str[] with slicing to extract the year value from Date (m/dd/yyyy): <em>
    STOCKS_SF1['Date'].str[-4::]</em></li>
</ul>
    7. Set variable <strong>STOCKS_DF1_FIRST7</strong> to the first <strong>7</strong> records of the DataFrame <strong>STOCKS_DF1</strong> using the <strong>head()</strong> function.
</span>

In [119]:
# INSERT CODE FOR STEPS 6 - 7
STOCKS_DF1['Year'] = STOCKS_DF1.Date.str[-4::]
STOCKS_DF1_FIRST7 = STOCKS_DF1.head(7)

In [120]:
# DO NOT MODIFY !!!
STOCKS_DF1_FIRST7

Date    Open    High     Low   Close    Volume  Name  Year
0   1/3/2017  115.80  116.33  114.76  116.15  28781865  AAPL  2017
1   1/4/2017  115.85  116.51  115.75  116.02  21118116  AAPL  2017
2   1/5/2017  115.92  116.86  115.81  116.61  22193587  AAPL  2017
3   1/6/2017  116.78  118.16  116.47  117.91  31751900  AAPL  2017
4   1/9/2017  117.95  119.43  117.94  118.99  33561948  AAPL  2017
5  1/10/2017  118.77  119.38  118.30  119.11  24462051  AAPL  2017
6  1/11/2017  118.74  119.93  118.60  119.75  27588593  AAPL  2017

<span style="color:blue">
    8. Create another new column for <strong>STOCKS_DF1 DataFrame</strong> called <strong>'Qtr'</strong> that contains the value of the quarter (<strong>1</strong>) <br>
    9. Set variable <strong>STOCKS_DF1_LAST10</strong> to the last <strong>10</strong> records of the DataFrame <strong>STOCKS_DF1</strong> using the <strong>tail()</strong> function.
</span>

In [121]:
# INSERT CODE FOR STEPS 8 - 9
STOCKS_DF1['Qtr'] = 1
STOCKS_DF1_LAST10 = STOCKS_DF1.tail(10)

In [122]:
# DO NOT MODIFY !!!
STOCKS_DF1_LAST10

Date   Open   High    Low  Close    Volume  Name  Year  Qtr
238  3/20/2017  45.67  45.95  45.16  45.23  21452575  ORCL  2017    1
239  3/21/2017  45.31  45.40  44.71  44.84  21974454  ORCL  2017    1
240  3/22/2017  45.13  45.45  44.63  44.79  14339677  ORCL  2017    1
241  3/23/2017  44.68  45.06  44.67  44.95  16190536  ORCL  2017    1
242  3/24/2017  44.92  45.09  44.58  44.65  13110178  ORCL  2017    1
243  3/27/2017  44.51  44.93  44.36  44.84   8933400  ORCL  2017    1
244  3/28/2017  44.83  45.03  44.66  44.69  14008754  ORCL  2017    1
245  3/29/2017  44.52  44.73  44.47  44.52  10636243  ORCL  2017    1
246  3/30/2017  44.45  44.74  44.37  44.68   7792510  ORCL  2017    1
247  3/31/2017  44.50  44.85  44.46  44.61  10652754  ORCL  2017    1

<span style="color:blue">
    10. Create another new column for <strong>STOCKS_DF1 DataFrame</strong> called <strong>'Perf'</strong>. This column will be created using a calculation. The column values are calculated as <strong>100 * ( 'Close' - 'Open') / 'Open'</strong> where 'Close' and 'Open' refer to the columns to use in the calculation.<br>
    11. Set variable <strong>STOCKS_DF1_LAST5</strong> to the last <strong>5</strong> records of the DataFrame <strong>STOCKS_DF1</strong> using the <strong>tail()</strong> function.
</span>

In [124]:
# INSERT CODE FOR STEPS 10 - 11
STOCKS_DF1['Perf'] = 100*(STOCKS_DF1['Close']-STOCKS_DF1['Open'])/STOCKS_DF1['Open']
STOCKS_DF1_LAST5 = STOCKS_DF1.tail()

In [125]:
# DO NOT MODIFY !!!
STOCKS_DF1_LAST5

Date   Open   High    Low  Close    Volume  Name  Year  Qtr  \
243  3/27/2017  44.51  44.93  44.36  44.84   8933400  ORCL  2017    1   
244  3/28/2017  44.83  45.03  44.66  44.69  14008754  ORCL  2017    1   
245  3/29/2017  44.52  44.73  44.47  44.52  10636243  ORCL  2017    1   
246  3/30/2017  44.45  44.74  44.37  44.68   7792510  ORCL  2017    1   
247  3/31/2017  44.50  44.85  44.46  44.61  10652754  ORCL  2017    1   

         Perf  
243  0.741406  
244 -0.312291  
245  0.000000  
246  0.517435  
247  0.247191

__SETTING COLUMN VALUES AS INDEX__

If you want to use one of the columns as the index for your DataFrame, you can do so using __set_index()__ <br>
If you want to reset the index back to the default values, you can do so using the __reset_index()__

    REF: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.set_index.html
    


<span style="color:blue">
    12. Use <strong>.set_index</strong> to set the <strong>'Date'</strong> column as the index for the DataFrame <strong>STOCKS_DF1</strong> <br>
    13. Set variable <strong>STOCKS_DF1_FIRST5</strong> to the first <strong>5</strong> records of the DataFrame <strong>STOCKS_DF1</strong> using the <strong>head()</strong> function. <br>
    14. Use <strong>.reset_index</strong> to reset the index of DataFrame <strong>STOCKS_DF1</strong> <br>
    15. Set variable <strong>STOCKS_DF1_FIRST8</strong> to the first <strong>8</strong> records of the DataFrame <strong>STOCKS_DF1</strong> using the <strong>head()</strong> function.
</span>

In [171]:
# INSERT CODE FOR STEPS 12 - 15
STOCKS_DF1 = STOCKS_DF1.set_index('Date')
STOCKS_DF1_FIRST5 = STOCKS_DF1.head()
STOCKS_DF1 = STOCKS_DF1.reset_index()
STOCKS_DF1_FIRST8 = STOCKS_DF1.head(8)

In [172]:
# DO NOT MODIFY !!!
STOCKS_DF1_FIRST5

Open    High     Low   Close    Volume  Name
Date                                                    
1/3/2017  115.80  116.33  114.76  116.15  28781865  AAPL
1/4/2017  115.85  116.51  115.75  116.02  21118116  AAPL
1/5/2017  115.92  116.86  115.81  116.61  22193587  AAPL
1/6/2017  116.78  118.16  116.47  117.91  31751900  AAPL
1/9/2017  117.95  119.43  117.94  118.99  33561948  AAPL

In [173]:
# DO NOT MODIFY !!!
STOCKS_DF1_FIRST8

Date    Open    High     Low   Close    Volume  Name
0   1/3/2017  115.80  116.33  114.76  116.15  28781865  AAPL
1   1/4/2017  115.85  116.51  115.75  116.02  21118116  AAPL
2   1/5/2017  115.92  116.86  115.81  116.61  22193587  AAPL
3   1/6/2017  116.78  118.16  116.47  117.91  31751900  AAPL
4   1/9/2017  117.95  119.43  117.94  118.99  33561948  AAPL
5  1/10/2017  118.77  119.38  118.30  119.11  24462051  AAPL
6  1/11/2017  118.74  119.93  118.60  119.75  27588593  AAPL
7  1/12/2017  118.90  119.30  118.21  119.25  27086220  AAPL